[package]
name = "thetvdb"
version = "0.1.0"
authors = ["Swagger Codegen team and contributors"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.1"
hyper = "0.12"
url = "2"
hyper-tls = "0.3"

[dev-dependencies]
tokio = "0.1"
