[package]
name = "thetvdb"
version = "0.1.0"
authors = ["sparky8251 <sparky@possumlodge.me>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.1"
hyper = "0.12"
url = "2"

[dev-dependencies]
tokio = "0.1"
hyper-tls = "0.3"
